name = "sg1" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "mssdk24-normal-useast2a.tiktokv.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "app.genflix.co.id.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "blue.blibli.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "zaintest.vuclip.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "m.pubgmobile.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "m.mobilelegends.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "web.poe.garena.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "dl.cvs.freefiremobile.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "m.googlevideo.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "s.youtube.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "test.noice.id.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "cdn.appsflayer.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "cdn.appsflayer.com.sg1.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "app.genflix.com.sg1.afrcloud.xyz"
custom_domain = true

[vars]
# UUID = "2aeee1cd-954a-4f69-b2c0-2de59511707b"
# PROXYIP = "138.2.104.102"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "2aeee1cd-954a-4f69-b2c0-2de59511707b"
